# Première visualisation du dataset

In [1]:
import numpy as np
import pandas as pd
# import sklearn

In [2]:
from matplotlib import pyplot as plt
from matplotlib import cm

## Affichage des 20 premiers joueurs

In [3]:
filename = 'dataset.csv'
names = ['Rk','Player','Nation','Pos','Squad','Comp','Age','Born','MP','Starts','Min','90s','Goals','Shots','SoT','SoT%','G/Sh','G/SoT','ShoDist','ShoFK','ShoPK','PKatt','PasTotCmp','PasTotAtt','PasTotCmp%','PasTotDist','PasTotPrgDist','PasShoCmp','PasShoAtt','PasShoCmp%','PasMedCmp','PasMedAtt','PasMedCmp%','PasLonCmp','PasLonAtt','PasLonCmp%','Assists','PasAss','Pas3rd','PPA','CrsPA','PasProg','PasAtt','PasLive','PasDead','PasFK','TB','PasPress','Sw','PasCrs','CK','CkIn','CkOut','CkStr','PasGround','PasLow','PasHigh','PaswLeft','PaswRight','PaswHead','TI','PaswOther','PasCmp','PasOff','PasOut','PasInt','PasBlocks','SCA','ScaPassLive','ScaPassDead','ScaDrib','ScaSh','ScaFld','ScaDef','GCA','GcaPassLive','GcaPassDead','GcaDrib','GcaSh','GcaFld','GcaDef','Tkl','TklWon','TklDef3rd','TklMid3rd','TklAtt3rd','TklDri','TklDriAtt','TklDri%','TklDriPast','Press','PresSucc','Press%','PresDef3rd','PresMid3rd','PresAtt3rd','Blocks','BlkSh','BlkShSv','BlkPass','Int','Tkl+Int','Clr','Err','Touches','TouDefPen','TouDef3rd','TouMid3rd','TouAtt3rd','TouAttPen','TouLive','DriSucc','DriAtt','DriSucc%','DriPast','DriMegs','Carries','CarTotDist','CarPrgDist','CarProg','Car3rd','CPA','CarMis','CarDis','RecTarg','Rec','Rec%','RecProg','CrdY','CrdR','2CrdY','Fls','Fld','Off','Crs','TklW','PKwon','PKcon','OG','Recov','AerWon','AerLost','AerWon%']
dataset = pd.read_csv(filename, sep=";", names=names)
dataset.head(20)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
0,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
1,1,Max Aarons,ENG,DF,Norwich City,Premier League,22,2000,34,32,...,0.03,1.41,1.16,0,0.06,0.03,5.53,0.47,1.59,22.7
2,2,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,34,1987,34,34,...,0,0.06,1.39,0,0.03,0,6.77,2.02,1.36,59.8
3,3,Salis Abdul Samed,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,29,...,0,0.36,1.24,0,0,0,8.76,0.88,0.88,50
4,4,Laurent Abergel,FRA,MF,Lorient,Ligue 1,29,1993,34,34,...,0.03,0.79,2.23,0,0,0,8.87,0.43,0.43,50
5,5,Charles Abi,FRA,FW,Saint-Etienne,Ligue 1,22,2000,1,1,...,0,2,0,0,0,0,4,2,0,100
6,6,Dickson Abiama,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,5,...,1.85,0.25,0.86,0,0,0,4.81,2.72,4.94,35.5
7,7,Matthis Abline,FRA,FW,Rennes,Ligue 1,19,2003,7,1,...,0,0.91,0,0,0,0,6.36,0,1.82,0
8,8,Tammy Abraham,ENG,FW,Roma,Serie A,24,1997,37,36,...,0.5,0.7,0.64,0.03,0.03,0,3.67,2.39,2.89,45.3
9,9,Luis Abram,PER,DF,Granada,La Liga,26,1996,8,6,...,0,0,0.97,0,0,0.16,4.03,1.94,2.42,44.4
10,10,Francesco Acerbi,ITA,DF,Lazio,Serie A,34,1988,30,29,...,0.14,0.04,0.43,0.04,0,0,10.7,2.84,1.6,64
11,11,Ragnar Ache,GER,MFFW,Eint Frankfurt,Bundesliga,23,1998,13,1,...,2.07,2.07,0.69,0,0,0,5.17,6.9,3.79,64.5
12,12,Mohamed Achi,FRA,MF,Nantes,Ligue 1,20,2002,1,0,...,0,0,10,0,0,0,10,0,0,0
13,13,Marcos Acuña,ARG,DF,Sevilla,La Liga,30,1991,31,26,...,0,4.94,1.55,0,0.04,0,8.92,1.31,1.47,47.1
14,14,Che Adams,SCO,FW,Southampton,Premier League,25,1996,30,23,...,0.31,0.48,0.4,0,0,0,5.29,2.47,4.89,33.5
15,15,Tyler Adams,USA,MF,RB Leipzig,Bundesliga,23,1999,24,12,...,0,0.2,1.07,0,0,0,10.6,1.53,0.8,65.7
16,16,Sargis Adamyan,ARM,FWMF,Hoffenheim,Bundesliga,29,1993,13,2,...,1.08,1.62,2.16,0,0,0,7.03,1.35,3.51,27.8
17,17,Martin Adeline,FRA,MFFW,Reims,Ligue 1,18,2003,8,2,...,0,0.51,3.08,0,0,0,10.3,0.51,2.05,20
18,18,Amine Adli,FRA,FWMF,Leverkusen,Bundesliga,22,2000,25,13,...,0.57,1.86,1.79,0,0,0,6.57,1.36,2.5,35.2
19,19,Yacine Adli,FRA,MFFW,Bordeaux,Ligue 1,21,2000,36,25,...,0.16,1.55,1.35,0,0,0,6.41,0.96,0.8,54.5

In [4]:
dataset.describe()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
count,2922,2922,2921,2922,2922,2922,2921,2922,2922,2922,...,2922,2922,2922,2922,2922,2922,2922,2922,2922,2922
unique,2922,2787,103,12,101,6,27,28,39,40,...,147,405,275,36,35,22,758,484,478,521
top,Rk,Marcelo,ESP,DF,Salernitana,Serie A,25,1997,1,0,...,0,0,0,0,0,0,0,0,0,0
freq,1,3,435,942,42,632,243,249,252,396,...,1489,750,539,2601,2450,2772,114,489,419,489

## Vérification d'éléments *parasites*

### Valeurs de types nulles

In [5]:
dataset.isnull()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2917,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2918,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2919,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2920,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2921,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
# On vérifie d'abord si au moins une valeur est nulle 
dataset.isnull().values.any()

True

In [7]:
# On compte le nombre de valeurs non nulles
dataset.isnull().sum().sum()

2

In [8]:
# On indique leur position
np.where(dataset.isnull())

(array([1532, 1532], dtype=int64), array([2, 6], dtype=int64))

On constate qu'il n' y a qu'une seule ligne qui contient des valeurs nulles

In [9]:
# On supprime la ligne
dataset = dataset.drop(index=1532)

In [10]:
dataset.isnull().values.any()

False

## Conversion des valeurs

In [32]:
# Affichage des types par colonnes
print(dataset.dtypes)

Rk         object
Player     object
Pos        object
Comp       object
Born       object
            ...
PKcon      object
OG         object
Recov      object
AerWon     object
AerLost    object
Length: 128, dtype: object

In [12]:
# Liste des élements par type
# col_int = ['']
# Conversion automatique de pandas
# dataset = dataset.convert_dtypes()
# dataset.apply(columns)

## Suppression de données non pertinentes pour le problème

### Colonnes qui ne concernent pas directement le problème

In [13]:
# Liste à revoir
to_delete = ['Nation', 'Squad', 'Age']
dataset = dataset.drop(columns=to_delete)

### Colonnes à pourcentages

In [25]:
# On récupère la liste des colonnes dont le nom ne contient pas '%'
cols = [name for name in list(dataset.columns.values) if '%' not in name]
print(cols)

['Rk', 'Player', 'Pos', 'Comp', 'Born', 'MP', 'Starts', 'Min', '90s', 'Goals', 'Shots', 'SoT', 'G/Sh', 'G/SoT', 'ShoDist', 'ShoFK', 'ShoPK', 'PKatt', 'PasTotCmp', 'PasTotAtt', 'PasTotDist', 'PasTotPrgDist', 'PasShoCmp', 'PasShoAtt', 'PasMedCmp', 'PasMedAtt', 'PasLonCmp', 'PasLonAtt', 'Assists', 'PasAss', 'Pas3rd', 'PPA', 'CrsPA', 'PasProg', 'PasAtt', 'PasLive', 'PasDead', 'PasFK', 'TB', 'PasPress', 'Sw', 'PasCrs', 'CK', 'CkIn', 'CkOut', 'CkStr', 'PasGround', 'PasLow', 'PasHigh', 'PaswLeft', 'PaswRight', 'PaswHead', 'TI', 'PaswOther', 'PasCmp', 'PasOff', 'PasOut', 'PasInt', 'PasBlocks', 'SCA', 'ScaPassLive', 'ScaPassDead', 'ScaDrib', 'ScaSh', 'ScaFld', 'ScaDef', 'GCA', 'GcaPassLive', 'GcaPassDead', 'GcaDrib', 'GcaSh', 'GcaFld', 'GcaDef', 'Tkl', 'TklWon', 'TklDef3rd', 'TklMid3rd', 'TklAtt3rd', 'TklDri', 'TklDriAtt', 'TklDriPast', 'Press', 'PresSucc', 'PresDef3rd', 'PresMid3rd', 'PresAtt3rd', 'Blocks', 'BlkSh', 'BlkShSv', 'BlkPass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'Touches', 'TouDefPen', 'TouDef3rd', 'TouMid3rd', 'TouAtt3rd', 'TouAttPen', 'TouLive', 'DriSucc', 'DriAtt', 'DriPast', 'DriMegs', 'Carries', 'CarTotDist', 'CarPrgDist', 'CarProg', 'Car3rd', 'CPA', 'CarMis', 'CarDis', 'RecTarg', 'Rec', 'RecProg', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'TklW', 'PKwon', 'PKcon', 'OG', 'Recov', 'AerWon', 'AerLost']

In [27]:
dataset = dataset.filter(items=cols)
dataset.shape

(2921, 130)

### Ratios

In [28]:
cols = [name for name in list(dataset.columns.values) if '/' not in name]
print(cols)

['Rk', 'Player', 'Pos', 'Comp', 'Born', 'MP', 'Starts', 'Min', '90s', 'Goals', 'Shots', 'SoT', 'ShoDist', 'ShoFK', 'ShoPK', 'PKatt', 'PasTotCmp', 'PasTotAtt', 'PasTotDist', 'PasTotPrgDist', 'PasShoCmp', 'PasShoAtt', 'PasMedCmp', 'PasMedAtt', 'PasLonCmp', 'PasLonAtt', 'Assists', 'PasAss', 'Pas3rd', 'PPA', 'CrsPA', 'PasProg', 'PasAtt', 'PasLive', 'PasDead', 'PasFK', 'TB', 'PasPress', 'Sw', 'PasCrs', 'CK', 'CkIn', 'CkOut', 'CkStr', 'PasGround', 'PasLow', 'PasHigh', 'PaswLeft', 'PaswRight', 'PaswHead', 'TI', 'PaswOther', 'PasCmp', 'PasOff', 'PasOut', 'PasInt', 'PasBlocks', 'SCA', 'ScaPassLive', 'ScaPassDead', 'ScaDrib', 'ScaSh', 'ScaFld', 'ScaDef', 'GCA', 'GcaPassLive', 'GcaPassDead', 'GcaDrib', 'GcaSh', 'GcaFld', 'GcaDef', 'Tkl', 'TklWon', 'TklDef3rd', 'TklMid3rd', 'TklAtt3rd', 'TklDri', 'TklDriAtt', 'TklDriPast', 'Press', 'PresSucc', 'PresDef3rd', 'PresMid3rd', 'PresAtt3rd', 'Blocks', 'BlkSh', 'BlkShSv', 'BlkPass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'Touches', 'TouDefPen', 'TouDef3rd', 'TouMid3rd', 'TouAtt3rd', 'TouAttPen', 'TouLive', 'DriSucc', 'DriAtt', 'DriPast', 'DriMegs', 'Carries', 'CarTotDist', 'CarPrgDist', 'CarProg', 'Car3rd', 'CPA', 'CarMis', 'CarDis', 'RecTarg', 'Rec', 'RecProg', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'TklW', 'PKwon', 'PKcon', 'OG', 'Recov', 'AerWon', 'AerLost']

In [29]:
dataset = dataset.filter(items=cols)
dataset.shape

(2921, 128)

### Suppression des lignes avec le nombre de matchs joués inférieur ou égale à 5

In [30]:
# A faire

### Autres raisons (plus ou moins arbitraires)
Voir le [mini-rapport](./IAS-projet-validation.pdf) de validation

In [31]:
# A faire